[project]
name = "python-api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ccxt>=4.4.99",
    "fastapi>=0.116.1",
    "pandas>=2.3.1",
    "uvicorn>=0.35.0",
    "xgboost>=3.0.3",
]
